### PR TITLE
Use event handler instead of 'javascript:fn' href

### PR DESCRIPTION
**Pull request by prtksxna**

### CODE REVIEW

**Comment by aaronpk** [comment]
What's the reason for this change?

**Comment by cweiske** [comment]
I would not merge this. It adds more indirection, and makes the code harder to understand.

**Comment by prtksxna** [comment]
Oops! I somehow missed notifications from this repo. There are a couple of reasons for the change

* Separation of content (HTML) and behavior/action (JS): Its similar to why we don't write CSS in the `style` attribute of elements.

* No mixing of languages: I am hoping to submit further patches to separate the JS files so that we are able to lint and test them separately.

* Consistency: The `<script>` tag at the bottom already attaches events to the DOM elements.

**Comment by prtksxna** [comment]
Hey @aaronpk, are you planning to look into this again?

**Pull request closed without merging**
